version: "3"
services:
  gten:
    image: kmint1819/gten:local
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/workspace
    network_mode: host
    stdin_open: true
    tty: true
